CREATE TABLE IF NOT EXISTS urls (
    id SERIAL PRIMARY KEY,
    full_url TEXT NOT NULL,
    short_url VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);