#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${MS_ACCOUNTS_USER} WITH PASSWORD '${MS_ACCOUNTS_PASSWORD}';
    CREATE DATABASE ${MS_ACCOUNTS_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${MS_ACCOUNTS_DB} TO ${MS_ACCOUNTS_USER};
EOSQL